# Generated by Django 5.0 on 2024-01-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Product name')),
                ('brand', models.CharField(max_length=250, verbose_name='Brand name')),
                ('product_id', models.CharField(max_length=250, verbose_name='Product ID')),
                ('image', models.CharField(max_length=250, verbose_name='Image URL')),
                ('price', models.CharField(max_length=250, verbose_name='Product price')),
                ('seo_url', models.CharField(max_length=250, verbose_name='Product URL')),
                ('user_manual', models.CharField(max_length=250, verbose_name='User manual')),
                ('pre_description', models.TextField(verbose_name='Pre description')),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('long_description', models.TextField(verbose_name='Long description')),
                ('seller', models.CharField(max_length=250, verbose_name='Product seller')),
                ('parent_category', models.CharField(max_length=250, verbose_name='Parent category')),
                ('parent_category_url', models.CharField(max_length=250, verbose_name='Parent category URL')),
            ],
        ),
    ]
